# Dataset selecionado
dataset: "GSE106302"

# Metadados
metadata:
  title: "Nr2f1 and BBSOAS syndrome"
  organism: "mus musculus"
  tissue: "hippocampus"
  description: "RNA-seq of Nr2f1 heterozygous mice"
  pmid: "31600777"
  sra: "SRP204099"

# Referência (URLs do genoma)
reference:
  fasta: "https://ftp.ensembl.org/pub/release-116/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz"
  gtf: "https://ftp.ensembl.org/pub/release-116/gtf/mus_musculus/Mus_musculus.GRCm39.115.gtf.gz"

# Design experimental
design: "~ genotype"
contrasts:
  - ["HET", "WT"]

# Recursos 
resources:
resources:
  fastqc:
    threads: 4
    mem: "4G"

  fastp:
    threads: 8
    mem: "8G"

  salmon:
    threads: 8
    mem: "8G"
    time: "02:00:00"

  deseq2:
    threads: 4
    mem: "16G"
    time: "04:00:00"

  enrichment:
    threads: 2
    mem: "8G"
    time: "01:00:00"
