# -*- coding: utf-8 -*-
"""gerar_metadados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMHp_anFTcSb-c7gHnOdEw0E9pwdwztD

#Geração dos metadados
##Tabela de metadados + arquivo yamal
Entre no estudo desejado, selecione todos os arquivos e "send to" --> "file" --> "Summary" e depois repita o processo trocando summary por "RunInfo"
"""

import pandas as pd

run_info= pd.read_csv("SraRunInfo.csv")
sra_result= pd.read_csv("sra_result.csv")

run_info.head(2)

nomes = run_info.columns.tolist()
print(nomes)

#Drop colunas nulas
run_info= run_info.dropna(axis=1, how="all")
#Colunas a manter: "Run", "download_path", "Experiment", "submission", "LibraryStrategy", "LibrarySelection", "LibrarySource", "LibraryLayout", "SRAStudy", "BioProject", "ProjectID", "Sample", "BioSample", "ScientificName", "SampleName","Tumor", "Submission"
run_info= run_info[["Run", "download_path", "Experiment", "LibraryLayout", "BioProject", "ProjectID", "Sample", "BioSample", "ScientificName", "SampleName","Tumor", "Submission"]]

#Padronizar a nomenclatura das colunas
run_info.columns= run_info.columns.str.lower()

run_info.head()

#########################################################

sra_result.head(2)

#Drop colunas nulas
sra_result= sra_result.dropna(axis=1, how="all")
#Colunas a remover: "Total Size, Mb", "Total RUNs", "Total Spots", "Total Bases"
sra_result= sra_result.drop(columns=["Total Size, Mb", "Total RUNs", "Total Spots", "Total Bases"])

#Padronizar a nomenclatura das colunas
sra_result.columns= sra_result.columns.str.lower().str.replace(" ","")

sra_result.head(2)

#Fazer o merge entre as duas tabelas através do "Experiment Accession"
info_metadados= pd.merge(run_info, sra_result, left_on="experiment", right_on="experimentaccession", how="inner")
info_metadados=info_metadados.drop(columns=["experimentaccession"])

info_metadados.head(2)

#Criar a tabela .tsv com o código SRR e "Experiment Title"
#Renomear as linhas Experiment Title de modo a deixar apenas WT ou HET
import re

def extrair_genotype(title):
  title_lower= str(title).lower()
  if 'wt' in title_lower:
    return 'WT'
  elif 'het' in title_lower:
    return 'HET'
  return None #se nenhum valor for encontrado

#Criar um novo dataframe
metadados_final= pd.DataFrame()
metadados_final['sample_id']= info_metadados['run']
metadados_final['genotype']= info_metadados['experimenttitle'].apply(extrair_genotype)

metadados_final.head()

#Salvar em .tsv
output_filename = "sample.tsv"
metadados_final.to_csv(output_filename, sep='\t', index=False)
print(f"Tabela'{output_filename}' salva")

